apiVersion: v1
kind: Secret
metadata:
  name: movie-app-secret
type: Opaque
stringData:
  MOVIE_API_TOKEN: "{{ .Values.appValues.movie.apiToken }}"
  REDIS_PASSWORD: "{{ .Values.global.redis.password }}"

